#!/bin/bash
id -u odoo &>/dev/null || useradd -m -d /home/odoo -U -r -s /bin/bash odoo

sudo -c "python3 -m venv /home/odoo/venv" odoo
sudo -c "mkdir -p /home/odoo/data" odoo
sudo -c "mkdir -p /home/odoo/src" odoo
sudo -c "git -C /home/odoo/src/odoo pull || clone https://www.github.com/odoo/odoo --depth=1 -b 15.0 /home/odoo/src/odoo" odoo
sudo -c "git -C /home/odoo/src/odoo pull || clone https://www.github.com/odoo/design-themes --depth=1 -b 15.0 /home/odoo/src/themes" odoo
#git -C /home/odoo/src/odoo pull || clone https://www.github.com/odoo/enterprise --depth=1 -b 15.0 /home/odoo/src/enterprise

python3 -m venv /opt/odoo.sh/jupyterlab
chown odoo -R /opt/odoo.sh
sudo -c "/opt/odoo.sh/jupyterlab/bin/pip install jupyterlab" odoo
sudo -c "/opt/odoo.sh/jupyterlab/bin/pip install markupsafe==2.0.1" odoo